// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/v1/users": {
    params: {};
  };
  "/api/v1/users/:userId": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/v1/users" | "/api/v1/users/:userId";
  };
  "routes/api.v1.users/route.ts": {
    id: "routes/api.v1.users";
    page: "/api/v1/users" | "/api/v1/users/:userId";
  };
  "routes/api.v1.users.$userId/route.ts": {
    id: "routes/api.v1.users.$userId";
    page: "/api/v1/users/:userId";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.v1.users": typeof import("./app/routes/api.v1.users/route.ts");
  "routes/api.v1.users.$userId": typeof import("./app/routes/api.v1.users.$userId/route.ts");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
};